# Generated by Django 5.2.5 on 2025-08-30 10:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PINCode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                ("pin_hash", models.CharField(max_length=128, verbose_name="PIN hash")),
                ("demande_id", models.UUIDField(verbose_name="Related demand ID")),
                ("expires_at", models.DateTimeField(verbose_name="Expires at")),
                ("is_used", models.BooleanField(default=False, verbose_name="Used")),
                (
                    "used_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="Used at"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pin_codes",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
            ],
            options={
                "verbose_name": "PIN Code",
                "verbose_name_plural": "PIN Codes",
                "db_table": "users_pincode",
                "indexes": [
                    models.Index(
                        fields=["user", "demande_id"],
                        name="users_pinco_user_id_ef3944_idx",
                    ),
                    models.Index(
                        fields=["expires_at"], name="users_pinco_expires_c7b0f9_idx"
                    ),
                    models.Index(
                        fields=["is_used"], name="users_pinco_is_used_95de22_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[("ADMIN", "Administrator"), ("TECH", "Technician")],
                        default="TECH",
                        max_length=10,
                        verbose_name="Role",
                    ),
                ),
                (
                    "language_pref",
                    models.CharField(
                        choices=[
                            ("fr-be", "French (Belgium)"),
                            ("nl-be", "Dutch (Belgium)"),
                            ("en", "English"),
                        ],
                        default="fr-be",
                        max_length=10,
                        verbose_name="Language preference",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Active")),
                (
                    "employee_id",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        unique=True,
                        verbose_name="Employee ID",
                    ),
                ),
                (
                    "department",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Department"
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="Phone number"
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
            ],
            options={
                "verbose_name": "Profile",
                "verbose_name_plural": "Profiles",
                "db_table": "users_profile",
                "indexes": [
                    models.Index(fields=["role"], name="users_profi_role_0cf86e_idx"),
                    models.Index(
                        fields=["employee_id"], name="users_profi_employe_41d6f3_idx"
                    ),
                ],
            },
        ),
    ]
